# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rides', '0003_auto_20170220_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/customer/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default='CUCEI', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
