# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0004_auto_20170222_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='order',
        ),
        migrations.AddField(
            model_name='route',
            name='people_in_route',
            field=models.ManyToManyField(to='Rides.Profile'),
        ),
    ]
