# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0005_auto_20170227_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
