# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0007_auto_20170227_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='chat_room',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Rides.Profile'),
        ),
    ]
